### ISSUE TITLE
打开后闪退（已安装node.js，crypto-js，py库）

### ISSUE THREAD

**Issue by lue611** [xoyi/jd_wbbny#13]
之前能正常，自从12号更新后就一直这样，怎么弄都无效
![Screenshot_2021-06-13-21-44-22-31](https://user-images.githubusercontent.com/43984245/121809772-b80abb00-cc90-11eb-94c5-99b09ca177b2.jpg)

**Comment by xoyi** [comment]
在放软件得文件夹里，在npm install crypto-js 下

**Comment by lue611** [comment]
原来如此，感谢，问题已解决
