### ISSUE TITLE
大佬,get_jdcookie.exe今天无法扫码获取ck了

### ISSUE THREAD

**Issue by acc20777** [xoyi/jd_wbbny#9]
大佬,get_jdcookie.exe今天无法扫码获取ck了

**Comment by xoyi** [comment]
不知道啥情况，我的还能用，不行就手动去抓把

**Comment by acc20777** [comment]
> 不知道啥情况，我的还能用，不行就手动去抓把

提示请升级最新版京东,可是app已经是最新版了

**Comment by xoyi** [comment]
> > 不知道啥情况，我的还能用，不行就手动去抓把
> 
> 提示请升级最新版京东,可是app已经是最新版了

那个提示没啥关系把，我这也提示了，但是可以正常获取，扫码完成图片没自动关闭，手动关闭下图片

**Comment by 13071558875** [comment]
> > > 不知道啥情况，我的还能用，不行就手动去抓把
> > 
> > 
> > 提示请升级最新版京东,可是app已经是最新版了
> 
> 那个提示没啥关系把，我这也提示了，但是可以正常获取，扫码完成图片没自动关闭，手动关闭下图片

一堆报错，拒绝访问

**Comment by q906373** [comment]
安装了npm install crypto-js还是自动管了，是怎么回事，之前正常，没安装这个的时候

**Comment by w-strive** [comment]
13号又出现火爆了
